version: '3.8'
services:
  postgres_db:
    container_name: postgres_db
    image: postgres:14-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_data
    ports:
      - "5432:5432"
    volumes:
      - volume_postgres_db_data:/var/lib/postgresql/data
#      - ./schema.sql:/docker-entrypoint-initdb.dl/schema.sql
    healthcheck:
      test: "pg_isready -U postgres | grep 'accepting connections' || exit 1"
      interval: 2s
      timeout: 20s
      retries: 10
volumes:
  volume_postgres_db_data:
    external: false