#database
POSTGRESQL_USERNAME: postgres
POSTGRESQL_PASSWORD: password
POSTGRESQL_DATABASE: db_data
POSTGRESQL_HOSTNAME: localhost
POSTGRESQL_PORT: 5432

#server
CONTAINER_PORT: 8085
ACTIVE_PROFILE: dev

#email
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: ${GMAIL_ID}
EMAIL_PASSWORD: ${GMAIL_SECRET}
VERIFY_EMAIL_HOST: http://localhost:8085